### ISSUE TITLE
URL namespace 'admin' isn't unique. 

### ISSUE THREAD

**Issue by deepanshumehtaa** [app-generator/django-coreui#2]
While i am installing this project i got an error

`?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
`

mainly, this error came when you try to make the migrations "python manage.py makemigrations".

**Comment by deepanshumehtaa** [comment]
Got the solution

you need to remove the extra line 
`path('admin/', admin.site.urls),          # Django admin route `
in core>urls.py

That's it !!!

**Comment by app-generator** [comment]
Hello @deepanshumehtaa, 
This is a common regression in the current version of all Django starters. 

Thanks for using this starter. 
Let us know if you need further assistance.
