### ISSUE TITLE
successfully migrated but not opening any page

### ISSUE THREAD

**Issue by ersanjay5991** [app-generator/django-coreui#9]
```
NoReverseMatch at /register/
Reverse for 'login' not found. 'login' is not a valid view function or pattern name

```

<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">NoReverseMatch at /register/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87);">Reverse for 'login' not found. 'login' is not a valid view function or pattern name.</pre>

Request Method: | GET
-- | --
http://127.0.0.1:8000/register/
2.2.10
NoReverseMatch
Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
/home/tbs/Documents/workspace/django-dashboard-coreui/venv_coreui/lib/python3.8/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 673
/home/tbs/Documents/workspace/django-dashboard-coreui/venv_coreui/bin/python
3.8.5
['/home/tbs/Documents/workspace/django-dashboard-coreui/django-dashboard-coreui',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/tbs/Documents/workspace/django-dashboard-coreui/venv_coreui/lib/python3.8/site-packages']
Sun, 18 Jul 2021 05:46:08 +0000

</div><div id="template" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(246, 246, 246); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

**Comment by app-generator** [comment]
Hello @ersanjay5991, 

Ty for using our products. 

- Can you provide more information regarding your migration? 
- If possible, please describe a test scenario to help us reproduce the problem.

**Comment by ersanjay5991** [comment]
Thanks  re migration working fine
